server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://cstudy.top:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: /*-CGP123cgp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


